<script>
    import {onMount} from "svelte"
    import {currentDiv} from "../lib/stores.js"

    onMount(()=>{
        window.div = document.getElementById("body")
    })
</script>

<div class="min-h-full min-w-full">
    <div id="body" class="mt-[20%] bg-white">
        <pre>
            a 
            a
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
        </pre>
    </div>
</div>