<script>
	import { onMount } from 'svelte';

	onMount(() => {
		window.div = document.getElementById('body');
	});
</script>

<div class="min-h-full min-w-full">
	<div id="body" class="mt-[20%] bg-slate-200">
		<pre>
            a 
            a
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a
            a 
            a 
            a
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a
            a 
            a 
            a 
            a 
            a 
            a 
            a 
            a 
        </pre>
	</div>
</div>
